stages:
  - deploy

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r 404.html assets index.html privacy.html robots.txt sitemap.xml styles.css terms.html public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
